### ISSUE TITLE
Feature/Todo Tracker

### ISSUE THREAD

**Issue by max397574** [startup-nvim/startup.nvim#5]
- [x] Cursor movement breaks at eof
- [ ] Cursor positioning not correct if displaywidth of line != strlen
- [ ] Position Cursor based on alignment
- [ ] Add icons and an option to disable them (folds)
- [ ] Highlight for folded sections
- [ ] Add screenshots to readme
